image/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^students/$', views.StudentView.as_view(), name='students'),
    url(r'^student/(?P<pk>\w+)$', views.StudentDetailView.as_view(), name='student-detail'),
    url(r'^courses/$', views.CourseListView.as_view(), name='courses'),
    url(r'^course/(?P<pk>[\w ]+)$', views.CourseDetailView.as_view(), name='course-detail'),
    url(r'^lecture/create/$', views.LectureCreate, name='lecture_create'),
    url(r'^course/create/$', views.CourseCreate.as_view(), name='course_create'),
    url(r'^student/create/$', views.StudentCreate.as_view(), name='student_create'),
    url(r'^teacher/create/$', views.TeacherCreate.as_view(), name='teacher_create'),
    url(r'^course/viewatt/(?P<pk>[\w ]+)/$', views.viewatt, name='viewatt'),

]

projectBTP/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application
from django.conf.urls import include

urlpatterns += [
    url(r'^image/', include('image.urls')),
]
#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/image/', permanent=True)),
]
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

image/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
import datetime
from django.utils import timezone

import uuid # Required for unique book instances


class Student(models.Model):


    roll_number = models.CharField(primary_key=True, max_length=25, help_text="Enter Roll Number")
    first_name = models.CharField(max_length=100, help_text="Enter First Name",null=True)
    last_name = models.CharField(max_length=100,help_text="Enter Second Name",null=True)
    student_image = models.ImageField(verbose_name=roll_number, help_text="Student Image",upload_to='media/students')
    course_id = models.ManyToManyField('Course',blank=True)
    #lecture_id = models.ManyToManyField('Lecture',blank=True)

    class Meta:
        ordering = ["roll_number"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.roll_number

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('student-detail', args=[str(self.roll_number)])




class Teacher(models.Model):
    first_name = models.CharField(max_length=100, help_text="Enter First Name")
    last_name = models.CharField(max_length=100, help_text="Enter Second Name")
    course_id = models.ManyToManyField('Course',blank=True)

    def __str__(self):
        """
        String for representing the Model object
        """
        return '%s %s' % (self.first_name, self.last_name)



class Course(models.Model):
    course_id = models.CharField(primary_key=True, max_length=10, help_text="Course")
    course_name = models.CharField(max_length=100, help_text="Course Name", blank=True)
    Teacher_name = models.ManyToManyField(Teacher,blank=True)
    student_roll_no = models.ManyToManyField(Student,blank=True)
    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.course_id

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """

        return reverse('course-detail',args= [str(self.course_id)])


class Lecture(models.Model):
    lecture_id = models.UUIDField(primary_key=True,default = uuid.uuid4,help_text="Unique ID for each and every Lecture")
    lecture_date_time = models.DateTimeField(help_text="Date of the Lecture",default=datetime.datetime.now)
    #student_name = models.ForeignKey(Student.first_name,blank=True,help_text="After a while")
    student_roll_no = models.ManyToManyField(Student,blank=True)
    course_id = models.ForeignKey(Course)
    lecture_image = models.ImageField(help_text="Image of Lecture",upload_to='media/lectures/')

    class Meta:
        ordering = ["-lecture_date_time"]

    def __str__(self):

        return '%s %s ' % (self.lecture_date_time, self.course_id)




image/forms.py
from django import forms
from .models import Lecture,Course, Student
import datetime


import uuid # Required for unique lecture instances

class Lectureform(forms.Form):
    course_id = forms.ModelChoiceField(queryset=Course.objects.all() ,help_text="Enter Course_ID")
    lecture_image = forms.ImageField(help_text = "Upload Image")
    lecture_id = forms.UUIDField( initial=uuid.uuid4,help_text="Unique ID for each and every Lecture")
    lecture_date_time = forms.DateTimeField(help_text="Date of the Lecture", initial=datetime.datetime.now)
    student_roll_no = forms.ModelMultipleChoiceField(queryset=Student.objects.all() ,required=False, help_text="Enter Course_ID")

image/views.py
from django.shortcuts import render
import os
# Create your views here.

from .models import Student, Teacher, Course, Lecture
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Lecture,Course,Student,Teacher
from django.http import HttpResponseRedirect,request, HttpResponse
from .forms import Lectureform

def viewatt(request,pk):
    students = Student.objects.filter(course_id=pk)
    student_data=[]

    for student in students:
        stu_d=[]
        stu_d.append(student.first_name)
        stu_d.append(student.roll_number)
        num_lec = Lecture.objects.filter(course_id=pk,student_roll_no=student.roll_number).count()
        stu_d.append(num_lec)
        student_data.append(stu_d)
    return render(
        request,
        'view_attendance.html',
        context={'student_data': student_data},
    )

def homepage(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_students = Student.objects.all().count()

    num_teachers = Teacher.objects.all().count()
    # Available books (status = 'a')
    num_lectures = Lecture.objects.count()
    num_course = Course.objects.count()  # The 'all()' is implied by default.

    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'home.html',
        context={'num_students': num_students, 'num_teachers': num_teachers,
                 'num_lectures': num_lectures, 'num_courses': num_course},
    )


class StudentView(generic.ListView):
    model = Student


class StudentDetailView(generic.DetailView):
    model = Student



class CourseListView(generic.ListView):
    model = Course #to add a lecture first course list has to be shown

class CourseDetailView(generic.DetailView):
    model = Course


def LectureCreate(request):
    if request.method == 'POST':
        form1 = Lectureform(request.POST, request.FILES)
        if form1.is_valid():
            course_id = form1.cleaned_data['course_id']
            lecture_image = form1.cleaned_data['lecture_image']
            lecture_id = form1.cleaned_data['lecture_id']
            lecture_date_time = form1.cleaned_data['lecture_date_time']
            student_roll_no = form1.cleaned_data['student_roll_no']
            t = Lecture(course_id = course_id, lecture_image=lecture_image, lecture_id=lecture_id, lecture_date_time = lecture_date_time,student_roll_no = student_roll_no)
            t.save()
            image_name=str(lecture_image)
            here = Lecture.objects.get(lecture_id = lecture_id )
            str_path = "projectBTP/media/lectures/"+image_name
            os.chdir("..")
            os.system("python ./demos/classifier.py infer --multi ./face_rec/generated-embeddings/classifier.pkl "+str_path)
            os.chdir("/root/openface/projectBTP")
            f = open("/root/openface/face_rec/output.txt")
            for line in iter(f):
                line = line.replace("\n", "")
                here.student_roll_no.add(Student.objects.get(roll_number=line))
            f.close()
              #mahak = "140001017"
              #aditi = "140001002"
              #here.student_roll_no.add(Student.objects.get(roll_number = mahak))
              #here.student_roll_no.add(Student.objects.get(roll_number=aditi))

            return HttpResponseRedirect('/image/')

    else:
        form1 = Lectureform()

    return render(request,'image/lecture_form.html', {'form1' : form1})

class CourseCreate(CreateView):
    model = Course
    fields = '__all__'

class StudentCreate(CreateView):
    model = Student
    fields = '__all__'

class TeacherCreate(CreateView):
    model = Teacher
    fields = '__all__'

image/templates/image/course_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Course Code: {{ course.course_id }}</h1>
  <p><strong>Course Name:</strong> {{ course.course_name }}</p>
  <li><a href="{% url 'viewatt' pk=course.course_id %}">View Attendance</a></li>
  <div style="margin-left:20px;margin-top:20px">
    <h4>Lectures</h4>
    <p><strong>Total Number of Lectures</strong> {{course.lecture_set.all.count}}</p>
    {% for copy in course.lecture_set.all %}
    <hr>
    <p><strong>Course Name</strong> {{copy.course_id}}</p>

    <p><strong>Lecture Time:</strong> {{copy.lecture_date_time}}</p>
    <p class="text-muted"><strong>Lecture Id:</strong> {{copy.lecture_id}}</p>
    <p><strong>Lecture Image</strong> {{copy.lecture_image}}</p>
    <p><strong>Students :</strong> {% for s_p in copy.student_roll_no.all %} {{ s_p }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
    {% endfor %}




  </div>
  {% endblock %}

image/templates/image/course_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Add" />
    
</form>
{% endblock %}

image/templates/image/course_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Course List</h1>

    {% if course_list %}
    <ul>

      {% for course in course_list %}
      <li>
        <a href="{{ course.get_absolute_url }}">{{ course.course_id }}</a> ({{course.course_name}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no courses in the college.</p>
    {% endif %}
{% endblock %}

image/templates/image/lecture_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ form1 }}
    </table>
    <input type="submit" value="Add" />
    
</form>
{% endblock %}

image/templates/image/student_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Roll Number: {{ student.roll_number }}</h1>
<p><strong>Roll Number:</strong> {{ student.roll_number }}</p>
<p><strong>First Name:</strong> {{ student.first_name }}</p>
<p><strong>Last Name:</strong> {{ student.last_name }}</p>
<p><strong>Image:</strong> {{ student.student_image }}</p>
<p><strong>Total Lectures:</strong> {{ student.lecture_set.all.count }}</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>Lectures</h4>

    {% for copy in student.lecture_set.all %}
    <hr>
    <p><strong>Course Name</strong> {{copy.course_id}}</p>

    <p><strong>Lecture Time:</strong> {{copy.lecture_date_time}}</p>
    <p class="text-muted"><strong>Lecture Id:</strong> {{copy.lecture_id}}</p>
    <p><strong>Lecture Image</strong> {{copy.lecture_image}}</p>
    {% endfor %}
  </div>
{% endblock %}

image/templates/image/student_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Add" />
    
</form>
{% endblock %}

image/templates/image/student_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Student List</h1>

    {% if student_list %}
    <ul>

      {% for student in student_list %}
      <li>
        <a href="{{ student.get_absolute_url }}">{{ student.roll_number }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no students registered.</p>
    {% endif %}       
{% endblock %}

image/templates/image/success_url.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Success</h1>
{% endblock %}

image/templates/image/teacher_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Add" />
    
</form>
{% endblock %}